version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
    - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "grupo2"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    expose:
      - "5432"
    ports:
      - "3002:5432"
    volumes:
      # So that our database's state is persisted locally
      - ./postgres-dump:/docker-entrypoint-initdb.d
      # Where our data will be persisted
      - my-db:/var/lib/posgresql

# Names our volume
volumes:
  my-db: